export const FACE_SNAPS_UI = {
  SNAP: "J'adore!",
  UNSNAP: "Je n'adore plus",
  BACK: '← Retour',
  VIEW: 'Découvrir',
  CONTINUE: 'Explorer le Maroc',
  LIKE: '♡',
  LIKED: '♥',
  SEARCH_PLACEHOLDER: 'Rechercher une ville, une région, un plat…',
  SEARCH_UNSPLASH: 'Rechercher une photo du Maroc…',
  NO_RESULTS: 'Aucun résultat trouvé',
  SORT_DATE: 'Plus récents',
  SORT_POPULARITY: 'Populaires',
  FILTER_ALL: 'Tout',
  COMMENT_PLACEHOLDER: 'Ajouter un conseil…',
  COMMENT_BTN: 'Publier',
  PROFILE_TITLE: 'Mon Carnet de Voyage',
  SAVE: 'Enregistrer',
  CANCEL: 'Annuler',
  LOAD_MORE: 'Charger plus…',
  CREATE_NEW_SNAP: 'Nouvelle découverte',
  CANCEL_CREATE: 'Annuler',
  ADD_SNAP: 'Ajouter',
  TITLE_PLACEHOLDER: 'Nom de la ville / du plat…',
  DESC_PLACEHOLDER: 'Description…',
  LOCATION_PLACEHOLDER: 'Région',
  SEARCH_UNSPLASH_BTN: 'Rechercher',
  LOADING: 'Chargement…',
  SEARCH_RESULTS_FOR: 'Aucun résultat pour',
  UNSPlASH_PHOTO: 'Photo Maroc',
};

export const APP_ROUTES = {
  FACE_SNAPS: 'decouvertes',
  LANDING: '',
  PROFILE: 'profil',
  LOGIN: 'connexion',
  REGISTER: 'inscription',
};
